FROM python:3.9

WORKDIR /app

COPY api/dependencies.txt /app/
RUN pip3 install -r dependencies.txt

COPY api/test_api.py /app/

EXPOSE 7777

COPY api/ /app/

ENV FLASK_APP=test_api.py

CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0", "--port=7777"]