FROM python:3.11

WORKDIR /app

COPY api/dependencies.txt /app/
RUN pip3 install -r dependencies.txt

COPY api/server.py /app/

EXPOSE 5000

COPY api/ /app/

ENV FLASK_APP=server.py

CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0", "--port=5000"]